export const ADD_NUMBER_ACTION = 'ADD_NUMBER_ACTION';
export const MINUS_NUMBER_ACTION = 'MINUS_NUMBER_ACTION';

export const GET_DATA_ACTION = 'GET_DATA_ACTION';
export const GET_DATA_ACTION_LOADING = 'GET_DATA_ACTION_LOADING';
